###
POST http://localhost:9000/api/auth/signin
Content-Type: application/json

{
"username": "sososo take",
"phone": 566768384,
"password": "nodehear!",
"location": "Biakia",
"roles": ["user", "moderator"]
}

###
GET http://localhost:9000/api/test/user
Content-Type: application/json
Authorization: { "x-access-token": eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1MWU5YTI3M2Y0OGI5MTlkZWRkNjE1ZiIsImlhdCI6MTY5NjUwNDM4MCwiZXhwIjoxNjk2NTkwNzgwfQ.BkdfdLttpOZTFF3MDViWxHvIZVBpy2yqFkAiY5SFjqM }


###
GET https://google.com